### ISSUE TITLE
undefined reference to Assimp::Importer

### ISSUE THREAD

**Issue by nikich340** [cumus/QT-3D-Model-Viewer#2]
What may cause this error during build? I am using win10 x64, Qt Creator 7.0.2, Qt kit 5.15.2 with MinGW x64 compiler.
Everything seems to be loaded in project fine (I mean assimp .h and .lib files).
```
g++ -Wl,-subsystem,windows -mthreads -o debug\QT3DModelViewer.exe @object_script.QT3DModelViewer.Debug  -LC:\DATA\QT_projects\QT-3D-Model-Viewer-master\QT3DModelViewer\Assimp\lib -lassimpd C:\DATA\Qt\5.15.2\mingw81_64\lib\libQt5Widgets.a C:\DATA\Qt\5.15.2\mingw81_64\lib\libQt5Gui.a C:\DATA\Qt\5.15.2\mingw81_64\lib\libQt5Core.a  -lmingw32 C:\DATA\Qt\5.15.2\mingw81_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.7.25-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 
debug/mesh.o: In function `Mesh::importModel(QString, MyOpenGLWidget*)':
C:\DATA\QT_projects\QT-3D-Model-Viewer-master\build-QT3DModelViewer-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/../QT3DModelViewer/mesh.cpp:35: undefined reference to `Assimp::Importer::Importer()'
C:\DATA\QT_projects\QT-3D-Model-Viewer-master\build-QT3DModelViewer-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/../QT3DModelViewer/mesh.cpp:50: undefined reference to `Assimp::Importer::GetErrorString() const'
C:\DATA\QT_projects\QT-3D-Model-Viewer-master\build-QT3DModelViewer-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/../QT3DModelViewer/mesh.cpp:54: undefined reference to `Assimp::Importer::~Importer()'
C:\DATA\QT_projects\QT-3D-Model-Viewer-master\build-QT3DModelViewer-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/../QT3DModelViewer/mesh.cpp:35: undefined reference to `Assimp::Importer::~Importer()'
debug/mesh.o: In function `Assimp::Importer::ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)':
C:\DATA\QT_projects\QT-3D-Model-Viewer-master\build-QT3DModelViewer-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/../QT3DModelViewer/Assimp/include/assimp/Importer.h:638: undefined reference to `Assimp::Importer::ReadFile(char const*, unsigned int)'
collect2.exe: error: ld returned 1 exit status
```

**Comment by cumus** [comment]
Thank you for your feedback. I'm currently working on figuring out your issue.

**Comment by cumus** [comment]
Turns out there was a mismatch between Assimp's resource architecture and the project's target architecture: trying to build for 32-bit with 64-bit library.

1. I recompiled Assimp's latest version and setup both 32&64-bit for debug and release.
2. Then I updated the way we organized resources with .qrc containers.
3. Found out Assimp is incompatible with .qrc as it needs the full path to access the .obj models.
4. Couldn't figure out an easy way to remove user dependancies from build configuration without messing up the .pro file.
5. Decided to write a single [Wiki page](https://github.com/cumus/QT-3D-Model-Viewer/wiki/Setting-Qt-User-Options) for this repo stating my build preferences. Models/ folder must be at the same level as the output .exe file.
6. Added qDebug logs with missing paths for easy feedback when a file can't be found.


BTW, now there are QMesh and Qt3DRender that remove this problem completly. No need for silly Assimp.

**Comment by nikich340** [comment]
Yes, I have seen QMesh stuff, but is there any minimal example of loading blender fbx file and setting up camera position? I haven't found any, official documentation doesn't have any for Qt C++.
Also I wonder if it's possible to move (animate)mesh "bones".

**Comment by cumus** [comment]
Couldn't believe how lacking the Qt documentation was. Now I understand why using Assimp.

I found out that Qt has tools ready for [Vertex Skinning](https://doc.qt.io/qt-6/quick3d-vertex-skinning.html), but the scenes must be parsed into QML code using Qt's [Balsam Asset Import Tool](https://doc.qt.io/qt-6/qtquick3d-tool-balsam.html). I would prefer adding C++ functionality to the imported assimp scene rather than having to deal with QML, but the choice is yours.

![Balsam example](https://user-images.githubusercontent.com/9050447/197741299-c7aaaf0e-04ed-424a-870e-33340af7e415.png)

**Comment by nikich340** [comment]
Yeah, that's why I asked about C++ documentation. Everything is for QML which I never use.. A pity :(
